### ISSUE TITLE
Support POST bypass cachemachine ?

### ISSUE THREAD

**Issue by fooyc** [glynnbird/cachemachine#12]
We have tried to use POST method by pass cachemachine to our app. However it don't return any response and error. Sometimes it able to response back sometimes not. It seems like not so stable.

When we use back normal POST method request. It does not have this issued happen.

Does anyone has facing this problem? Please advice !

**Comment by glynnbird** [comment]
Only GET requests are cached. I've tried using the cachemachine to do posts and they work (but they are not cached - only GET requests are cached).

**Comment by fooyc** [comment]
Do you have any plan to support POST in cached ?
